# Generated by Django 3.0.5 on 2020-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedisServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name to identify the server", max_length=255, unique=True
                    ),
                ),
                ("host", models.CharField(help_text="redis server host", max_length=255)),
                ("port", models.PositiveIntegerField(default=6379, help_text="redis server port")),
                (
                    "password",
                    models.CharField(blank=True, help_text="redis server host", max_length=255),
                ),
            ],
            options={"ordering": ("-name",),},
        ),
    ]
