# Generated by Django 3.0.5 on 2020-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redisserver',
            name='port',
            field=models.PositiveIntegerField(help_text='redis server port'),
        ),
    ]
