# Generated by Django 3.0.5 on 2020-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_redisserver_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redisserver',
            name='port',
            field=models.PositiveIntegerField(default=6379, help_text='redis server port'),
        ),
    ]
