# Generated by Django 3.0.5 on 2020-04-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200418_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redisserver',
            options={'ordering': ('-name',)},
        ),
    ]
